# 开发环境配置
server:
  port: 80
springdoc:
  api-docs:
    enabled: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  data:
    redis:
      host:
      port:
  influx:
    url:
    user:
    password:
  mail:
    host: smtp.163.com
    username:
    password:
  rabbitmq:
    addresses:
    username:
    password:
    virtual-host: /
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    jwt:
      key: 'abcdefghijklmn'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 5
      limit: 1000
      block: 30
    cors:
      origin: '*'
      credentials: false
      methods: '*'
